import os
import json
import random
from datetime import datetime
from src.state import GraphState
from src.logger import log_agent_action
from src.registry import upsert_incident

def create_incident_node(state: GraphState) -> GraphState:
    """
    Creates a mock Git Incident ticket after drift detection.
    """
    severity = state.get("severity", "Unknown")
    entity = state.get("offending_entity", "Unknown")
    incident_id = state.get("incident_id")
    
    # Use existing ID if it matches the format, otherwise generate new
    if incident_id and incident_id.startswith("GIT-INC-"):
        ticket_id = incident_id
    else:
        ticket_id = f"GIT-INC-{random.randint(1000, 9999)}"
    
    msg = f"Opened Incident Ticket {ticket_id} for {entity} ({severity})"
    log_agent_action("ticketer", "Incident Created", msg)
    
    # Initialize the physical evidence file immediately as requested
    evidence_dir = "data/evidence"
    os.makedirs(evidence_dir, exist_ok=True)
    file_path = os.path.join(evidence_dir, f"{ticket_id}.md")
    
    logs = state.get("logs", [])
    initial_evidence = f"""# Incident Report: {ticket_id}
**Status:** OPEN (Awaiting Analysis/Remediation)
**Severity:** {severity}
**Detected Entity:** {entity}
**Detection Time:** {datetime.now().isoformat()}

## Summary
The system has detected a potential compliance violation and initialized this evidence file. 

## Technical Details
The following raw logs were captured during the detection phase.

### Raw Forensic Logs
```json
{json.dumps(logs, indent=2)}
```

---
*This is an automated evidence file generated by Audit Aura.*
"""
    with open(file_path, "w") as f:
        f.write(initial_evidence)
    
    log_agent_action("ticketer", "Evidence Initialized", f"Initial report created at {file_path}")

    execution_entry = {
        "node": "ticketer",
        "message": msg,
        "timestamp": datetime.now().isoformat(),
        "details": {"ticket_id": ticket_id, "type": "incident"}
    }
    
    # Update incident registry
    upsert_incident(incident_id=ticket_id, incident_ticket_id=ticket_id)
    
    return {"incident_ticket_id": ticket_id, "execution_log": [execution_entry]}

def create_change_node(state: GraphState) -> GraphState:
    """
    Creates a mock Git Change ticket before/during remediation.
    """
    ticket_id = f"GIT-CHG-{random.randint(1000, 9999)}"
    msg = f"Opened Change Ticket {ticket_id} for remediation tracking."
    log_agent_action("ticketer", "Change Created", msg)
    
    execution_entry = {
        "node": "ticketer",
        "message": msg,
        "timestamp": datetime.now().isoformat(),
        "details": {"ticket_id": ticket_id, "type": "change"}
    }
    
    incident_id = state.get("incident_id")
    if incident_id:
        upsert_incident(incident_id=incident_id, change_ticket_id=ticket_id)
    
    return {"change_ticket_id": ticket_id, "execution_log": [execution_entry]}

def resolve_incident_node(state: GraphState) -> GraphState:
    """
    Links the Change to Incident and resolves the Incident.
    """
    status = state.get("validation_status", "Unknown")
    ticket_id = state.get("incident_ticket_id", "Unknown")
    
    if status == "Success":
        msg = f"Incident {ticket_id} resolved and closed."
    else:
        msg = f"Remediation failed. Incident {ticket_id} remains open."
        
    log_agent_action("ticketer", "Resolution", msg)
    
    execution_entry = {
        "node": "ticketer",
        "message": msg,
        "timestamp": datetime.now().isoformat(),
        "details": {"status": "resolved" if status == "Success" else "open"}
    }
    
    incident_id = state.get("incident_id")
    if incident_id:
        upsert_incident(
            incident_id=incident_id,
            status="Resolved" if status == "Success" else "In Progress"
        )
    
    return {"execution_log": [execution_entry]}
